# .github/workflows/daily-run.yml
name: Daily Answer Script

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      ACCOUNT: ${{ secrets.ACCOUNT }}
      PASSWORD: ${{ secrets.PASSWORD }}
      KEY: ${{ secrets.KEY }}
      IV: ${{ secrets.IV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Answer Script
        run: bun run index.ts

      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="${{ secrets.ACCOUNT }}答题成功"
